# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Infrastructure/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Application\Handler\Usuario\:
        resource: '../src/Application/Handler/Usuario/*Handler.php'
        tags: [ 'app.handler' ]

    App\Application\Handler\Transacao\:
        resource: '../src/Application/Handler/Transacao/*Handler.php'
        tags: [ 'app.handler' ]

    App\Application\Handler\HandlerChainBuilder:
        arguments:
            $handlers: !tagged_iterator app.handler

    handler_chain:
        class: App\Application\Handler\AbstractHandler
        factory: ['@App\Application\Handler\HandlerChainBuilder', 'buildChain']

    App\Presentation\API\Controller\UsuarioController:
        arguments:
            $handlerChain: '@handler_chain'

    App\Presentation\API\Controller\TransacaoController:
        arguments:
            $handlerChain: '@handler_chain'

    App\Domain\Usuario\Repository\UsuarioRepository:
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments:
            - App\Domain\Usuario\Entity\Usuario

    App\Domain\Usuario\Services\UsuarioService:
        arguments:
            $encoder: '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'
            $usuarioRepository: '@App\Domain\Usuario\Repository\UsuarioRepository'
            $carteiraService: '@App\Domain\Transacao\Services\CarteiraService'

    App\Domain\Transacao\Repository\CarteiraRepository:
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments:
            - App\Domain\Transacao\Entity\Carteira

    App\Domain\Transacao\Services\CarteiraService:
        arguments:
            $carteiraRepository: '@App\Domain\Transacao\Repository\CarteiraRepository'

    App\Domain\Transacao\Repository\TransacaoRepository:
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments:
            - App\Domain\Transacao\Entity\Transacao

    App\Domain\Transacao\Services\TransacaoService:
        arguments:
            $entityManager: '@Doctrine\ORM\EntityManagerInterface'
            $usuarioRepository: '@App\Domain\Usuario\Repository\UsuarioRepository'
            $client: '@App\Infrastructure\Service\AutorizacaoClient'

    App\Infrastructure\Service\AutorizacaoClient:
        arguments:
            $client: '@http_client'


